### ISSUE TITLE
就是直接在secrets填的是什么格式的数据啊？

### ISSUE THREAD

**Issue by Evanlovea** [zgzhengSEU/HWStatusCodeAutoQuery#1]
UID	用户名
PASSWORD	密码
EMAIL	邮件地址
EMAILCODE	邮件授权码

**Comment by zgzhengSEU** [comment]
和你登录华为官网时填写的数据一样。
账号名，账号密码
字符串格式吧

**Comment by Evanlovea** [comment]
UID：“xxxx”，
PASSWORD：“”这种格式吗

**Comment by zgzhengSEU** [comment]
比如UID，就在Name那一栏填上UID，然后再secret填写用户名，比如手机号，或者登录邮箱什么，直接填写
![image](https://user-images.githubusercontent.com/62554593/201269630-fa7b0783-6b64-496c-a554-1b29ddf7065b.png)
