### ISSUE TITLE
脚本运行失败

### ISSUE THREAD

**Issue by Jas-zheng** [zgzhengSEU/HWStatusCodeAutoQuery#2]
![image](https://user-images.githubusercontent.com/58075252/201278022-ce5a04ef-d478-4dab-a015-e8dad8204f49.png)
请问这个如何解决

**Comment by zgzhengSEU** [comment]
操作取消？secret都填写了吗？取消自己仓库的star，再点star重新启动一次脚本看看

**Comment by Jas-zheng** [comment]
ok，重新star后就成功了，感谢
