### ISSUE TITLE
为什么要设置六小时切换一次任务？

### ISSUE THREAD

**Issue by yyhyplxyz** [zgzhengSEU/HWStatusCodeAutoQuery#3]
谢谢大佬的分享。我看有AutoQuery1-4，是不是每间隔24小时要手动重启一次github的action呀？

**Comment by zgzhengSEU** [comment]
因为GitHub Actions 功能，每个job最多运行6小时，超过就会被系统取消。GitHub服务器不可能让你一直白嫖啊。所以设置4个连续的job，可以运行24h。然后整个workflow是每天定时启动的。定时启动时间可以自己在AutoQuery.yml文件里修改。点star作为一种触发workflow方式，可以用来测试。
