### ISSUE TITLE
一个致命缺陷？

### ISSUE THREAD

**Issue by penghuima** [zgzhengSEU/HWStatusCodeAutoQuery#4]
> 作者做的工作很优秀，利用github action完成爬虫功能，赞👍。但我有一个问题想和作者讨论下
作者有测试过更改一些if条件，比如修改  if res_list[0].split(':')[0] == '"INTERVIEW_TYPE"'，来测试自己能爬虫成功以及成功给自己发邮件吗？我看了下作者job执行日志，根本就爬虫失败，拿不到页面值的，job跑的日志如下

![image](https://user-images.githubusercontent.com/43670120/202136513-a457aaac-0183-40c5-9233-e47c6bfbb015.png)

**这段爬虫代码我看了下，我提出我自己的建议，代码每个人使用的时候，应该修改自己的deviceFingerInfo字段value值**
![image](https://user-images.githubusercontent.com/43670120/202138317-56bb6b0e-dc2f-4b90-949b-154100766f0d.png)
**关于deviceFingerInfo字段value值就登陆自己浏览器查找就是了**
![image](https://user-images.githubusercontent.com/43670120/202139613-dd54116b-3b92-4c4e-a7c3-8a8f1253804e.png)

看到那么多人使用，就发表一下自己的浅见

**Comment by zgzhengSEU** [comment]
谢谢提出建议，目前已经修复，经过测试可以正常使用了

**Comment by penghuima** [comment]
🚀🚀🚀，这不怕网友们第一时间收不到状态码改变的消息嘛😬

**Comment by lywly** [comment]
> 谢谢提出建议，目前已经修复，经过测试可以正常使用了

老哥，已拉取了最新库，删掉Action，重新Star，还是一样的错误啊，还需要更改什么吗？

```
当前状态码为：
"code":"huawei.rec.portal.10010009"
"httpCode":0
"entity":null
"message":"您的登录已失效，请重新登录，您也可以新打开一个页签登录，再回到本页面操作，请不要在同一浏览器里登录多个账户"
"faultUid":""
"stackTrace":"
```

**Comment by penghuima** [comment]
> 老哥，已拉取了最新库，删掉Action，重新Star，还是一样的错误啊，还需要更改什么吗？
> 
> ```
> 当前状态码为：
> "code":"huawei.rec.portal.10010009"
> "httpCode":0
> "entity":null
> "message":"您的登录已失效，请重新登录，您也可以新打开一个页签登录，再回到本页面操作，请不要在同一浏览器里登录多个账户"
> "faultUid":""
> "stackTrace":"
> ```
@lywly 你需要做的是在你的仓库 https://github.com/lywly/HWStatusCodeAutoQuery/blob/main/query.py#L55 这里将deviceFingerInfo字段value值改成你自己的，不要再使用“d36a786626c0c6417af75105301d425b”这个了， 自己deviceFingerInfo字段值查询我已经在上面说了如何查询了，仓库作者可能还没有第一时间更新readme

**Comment by penghuima** [comment]
> deviceFingerInfo

你这都账号都已经登陆上去了，你需要先退出登陆，停留在登陆页面，下面这个页面
![image](https://user-images.githubusercontent.com/43670120/202609956-5d324059-6435-4671-a6af-6468446397a9.png)
然后 F12打开源码模式，在元素那一栏按 ctrl+F 差找这个字段 deviceFingerInfo
![image](https://user-images.githubusercontent.com/43670120/202610204-7a7c782c-90f5-4837-824c-4ccb258b39ca.png)
然后将这个值替换成你自己的，再重启job就可以了，不然模拟登陆一直显示登陆失败的

**Comment by lywly** [comment]
啊这，，万分感谢！已改

**Comment by zgzhengSEU** [comment]
应该不用修改deviceFingerInfo吧，这个deviceFingerInfo也是用的原作者的deviceFingerInfo。在现在最新修改的代码里面，登录查询后及时退出，我测试挺稳定，没出现问题了。

**Comment by zgzhengSEU** [comment]
应该不用修改deviceFingerInfo吧，这个deviceFingerInfo也是用的原作者的deviceFingerInfo。在现在最新修改的代码里面，登录查询后及时退出，"您的登录已失效，请重新登录，您也可以新打开一个页签登录，再回到本页面操作，请不要在同一浏览器里登录多个账户" 这个问题就没有再出现了。测试挺稳定。

**Comment by zgzhengSEU** [comment]
我这里测试没问题， 有没有其他用户测试下看看

**Comment by zgzhengSEU** [comment]
那可以把deviceFingerInfo也加到action secret里面

**Comment by penghuima** [comment]
> 那可以把deviceFingerInfo也加到action secret里面

我看到你修改代码之后（修改了退出登陆url），job跑成功了，应该都不用加了，也挺麻烦的，如果后续其他人的job跑成功就不加了（我感觉应该是可以跑通的）

**Comment by lywly** [comment]
作者 @zgzhengSEU ，提个小建议：

> 目前`Action`需要运行5小时才能看到`Run`的输出，能不能改成实时输出`Log`呢，谢谢

![Snipaste_2022-11-18_14-48-44](https://user-images.githubusercontent.com/31092835/202639469-1ee85357-2c4f-450a-beab-aaa6733fe391.png)

**Comment by penghuima** [comment]
其实不是打广告啊，如果网友感兴趣可以了解一下【函数计算】，这里举阿里fc产品为例： https://www.aliyun.com/product/fc.

将函数代码直接部署到云端，设置一个触发器，触发函数执行时间间隔可自己任意设置，这种小需求也不会收费，有很多薅羊毛的空间，唯一麻烦的可能就是需要接触一个新的领域及概念，如果大家感兴趣可以看一看，多了解 些新东西也挺有意思的.

下面附一个帮朋友查询函数的图
![image](https://user-images.githubusercontent.com/43670120/202640909-4081dd11-6332-480d-985e-8b2a47e4ad0c.png)

**Comment by zgzhengSEU** [comment]
已经将deviceFingerInfo更新到最新的代码里面了，"您的登录已失效，请重新登录，您也可以新打开一个页签登录，再回到本页面操作，请不要在同一浏览器里登录多个账户" 这个问题应该可以解决了。如果有用户出现问题可以再提issues。

**Comment by zgzhengSEU** [comment]
> 作者 @zgzhengSEU ，提个小建议：
> 
> > 目前`Action`需要运行5小时才能看到`Run`的输出，能不能改成实时输出`Log`呢，谢谢
> 
> ![Snipaste_2022-11-18_14-48-44](https://user-images.githubusercontent.com/31092835/202639469-1ee85357-2c4f-450a-beab-aaa6733fe391.png)

已经添加了快速测试job，可以试试。

**Comment by lywly** [comment]
最新代码，添加了DFI了，依然老错误，难啊，比阿根廷还难
![Snipaste_2022-11-22_21-03-05](https://user-images.githubusercontent.com/31092835/203320856-1341b19f-a1a2-4f3d-aa88-0e9a58f11c81.png)
