### ISSUE TITLE
发送邮件有问题

### ISSUE THREAD

**Issue by lxambulance** [zgzhengSEU/HWStatusCodeAutoQuery#5]
试了一下总是收不到邮件，但是本地单独运行发送函数sendEmail正常，可以收到。

尝试debug一下，发现是main里面host_server初始化判断和github action环境变量设置的问题，secrets不填STMP会导致环境变量STMP设置为空，最终发送邮件地址为空。

建议：STMP设置必填 或 初始化逻辑改为判字符串是否为空

**Comment by zgzhengSEU** [comment]
已修正，之前SMTP错误拼写成STMP，在代码中修正了，但忘记在workflow文件里修正，导致环境变量没有加载。目前已经修正为SMTP并添加环境变量。
