### ISSUE TITLE
SMTP仍有问题

### ISSUE THREAD

**Issue by lxambulance** [zgzhengSEU/HWStatusCodeAutoQuery#7]
:joy:

不是SMTP拼没拼写对的问题。

有尝试过选填字段不填secrets.SMTP和（或）secrets.STMP吗？

邮件根本发不出去，初始化host_server一直为空字符串，那个if ... in os.env的判断恒真，没啥用。

**Comment by fanghaotianHT** [comment]
smtplib.SMTPServerDisconnected: please run connect() first没搞懂这个错误是什么原因

**Comment by lxambulance** [comment]
就是你host_server一直是空的，它服务器网络连接没连上。

**Comment by lxambulance** [comment]
那我不知道了。。。我是没填会报这个错

**Comment by zgzhengSEU** [comment]
pull最新的代码试试，我修改了一些地方，添加了快速测试，可以重新star快速测试一下，看看还有没有问题。

**Comment by zgzhengSEU** [comment]
之前的代码逻辑确实有问题，最新的代码我加了 if  ... == '' 来判空了。可以避免一直是True
